### ISSUE TITLE
Integrating fireback in this project

### ISSUE THREAD

**Issue by torabian** [mewebstudio/java-spring-boot-boilerplate#7]
Hi @mewebstudio, Creator of fireback framework.
I am adding Java Support for fireback to generate a lot of boilerplate code and relations, are you interested also I can add it into this project instead of keeping a repository on my own?

https://github.com/torabian/fireback

**Comment by mewebstudio** [comment]
Hi @torabian,
You are free to use the code and if you need support, I will try to help.
